# Generated by Django 5.1.6 on 2025-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('packager_name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='uploads')),
                ('image2', models.ImageField(upload_to='uploads')),
                ('image3', models.ImageField(upload_to='uploads')),
                ('image4', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
