# Generated by Django 5.1.6 on 2025-02-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_packages_image1_alter_packages_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_verified',
            field=models.CharField(default='Not Verified', max_length=100),
        ),
    ]
