# Generated by Django 5.1.6 on 2025-02-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_packages_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='is_verified',
            new_name='verification',
        ),
    ]
