# Generated by Django 5.1.6 on 2025-02-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bookingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='destination',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='packager_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
