# Generated by Django 5.1.6 on 2025-02-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bookingdetails_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
