# Generated by Django 5.1.6 on 2025-02-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_packages_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
