# Generated by Django 5.1.6 on 2025-02-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bookingdetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='price',
        ),
    ]
